-- P1 Warlock Guide — Horde warlock PATH (3.3.5a, Questie-verified IDs)

P1WG = P1WG or {}
P1DG = P1WG

P1WG.PATH_STEPS = {
    { level = 10, impact = 100, type = "spell", spellId = 697,
      text = "Summon Voidwalker — complete Durotar/Barrens pet quest" },
    { level = 14, impact = 95, type = "spell", spellId = 980,
      text = "Curse of Agony — second DoT on every pull" },
    { level = 18, impact = 90, type = "gear", equipSlot = 18, minIlvl = 12, itemId = 5210,
      text = "AH/vendor: Burning Wand (+shadow dmg)" },
    { level = 24, impact = 85, type = "spell", spellId = 689,
      text = "Drain Life — filler + self-heal while DoTs tick" },
    { level = 30, impact = 80, type = "spell", spellId = 691,
      text = "Summon Felhunter — dispels + better vs casters" },
    { level = 32, impact = 78, type = "spell", spellId = 5740,
      text = "Rain of Fire — AoE quest packs" },
    { level = 34, impact = 76, type = "hint", maxLevel = 36,
      text = "Rotation: CoA → Corruption → SB → Drain Life <40% HP" },
    { level = 36, impact = 74, type = "gear", equipSlot = 13, minIlvl = 50, itemId = 12930,
      text = "AH: Briarwood Reed trinket (Int spike)" },
    { level = 40, impact = 72, type = "spell", spellId = 19028,
      text = "Soul Link — survivability for long chains" },
    { level = 42, impact = 70, type = "spell", spellId = 6789,
      text = "Death Coil — panic button / execute" },
    { level = 46, impact = 68, type = "gear", equipSlot = 16, minIlvl = 42, itemId = 9427,
      text = "AH: Golem Skull Staff or +Int staff upgrade" },
    { level = 50, impact = 66, type = "spell", spellId = 28176,
      text = "Fel Armor — armor + spell power buff" },
    { level = 52, impact = 64, type = "spell", spellId = 17877,
      text = "Shadowburn — instant finisher / moving cast" },
    { level = 54, impact = 62, type = "gear", equipSlot = 13, minIlvl = 35, itemId = 11815,
      text = "Optional AH: Hand of Justice (long-term BiS)" },
    { level = 56, impact = 60, type = "consume", itemId = 13446, goal = 15,
      text = "AH: Major Healing Potions before Outland" },
    { level = 58, impact = 58, type = "hint", maxLevel = 60,
      text = "Pre-Outland: bank mount gold · buy Outland green staff/wand on AH (ilvl 80+ +SP/int; 2H staff = biggest spike)" },
    { level = 58, impact = 57, type = "hint", maxLevel = 62,
      text = "AH: any solid +SP 2H staff (ilvl 90-110 greens common in Hellfire)",
      flavor = "Staff ilvl beats most armor for locks." },
    { level = 60, impact = 56, type = "spell", spellId = 30108,
      text = "Unstable Affliction — third DoT (1.5s cast; anti-dispel silence on break)" },
    { level = 62, impact = 55, type = "spell", spellId = 603,
      text = "Curse of Doom — long fight opener (60s CD big nuke after 1 min)" },
    { level = 62, impact = 54, type = "gear", equipSlot = 13, minIlvl = 90, itemId = 25786,
      text = "Quest/AH: Hypnotist's Watch trinket (Hellfire; threat reduce)" },
    { level = 64, impact = 52, type = "spell", spellId = 30283,
      text = "Shadowfury — stun AoE for Hellfire packs (NOT 47897 Shadowflame cone; ranks 30283/30413/47847)" },
    { level = 66, impact = 50, type = "gear", equipSlot = 18, minIlvl = 100, itemId = 25806,
      text = "Quest/AH: Nethekurse's Rod wand (+SP; SLabs/Shattered Halls)" },
    { level = 68, impact = 48, type = "gear", equipSlot = 16, minIlvl = 115, itemId = 31308,
      text = "AH: The Bringer of Death 2H staff (+121 SP) or equivalent high-ilvl staff",
      flavor = "Staff ilvl > most armor slots." },
    { level = 70, impact = 46, type = "hint", maxLevel = 72,
      text = "Northrend: Borean Tundra start · stack haste/spirit · keep Fel Armor (28176) up" },
    { level = 71, impact = 45, type = "spell", spellId = 59164,
      text = "Haunt — Affliction core (snapshot DoTs; learn at 71)" },
    { level = 72, impact = 44, type = "spell", spellId = 47893,
      text = "Fel Armor rank 2 — upgrade armor/SP buff (replaces 28176 rank)" },
    { level = 74, impact = 42, type = "spell", spellId = 47836,
      text = "Seed of Corruption — NR AoE packs (affliction/destro hybrid)" },
    { level = 76, impact = 40, type = "gear", equipSlot = 18, minIlvl = 200, itemId = 44310,
      text = "AH: Namlak's Supernumerary Sticker wand (ilvl 200 +SP)" },
    { level = 78, impact = 38, type = "gear", equipSlot = 16, minIlvl = 200, itemId = 45128,
      text = "AH: Silvery Sylvan Stave or ilvl 200+ 2H staff",
      flavor = "Staff ilvl still king for locks in NR." },
    { level = 80, impact = 36, type = "hint", maxLevel = 80,
      text = "Cap NR: stock frost oil / runed orbs · AH ilvl 232+ staff before ICC blues" },
}

P1WG.GOLD_AH_BIS = {
    { levelMin = 10, levelMax = 20, itemId = 5210, label = "Wand", equipSlot = 18, minIlvl = 12 },
    { levelMin = 16, levelMax = 28, itemId = 3902, label = "Staff", equipSlot = 16, minIlvl = 18 },
    { levelMin = 34, levelMax = 50, itemId = 12930, label = "Trinket", equipSlot = 13, minIlvl = 50 },
    { levelMin = 44, levelMax = 55, itemId = 9427, label = "Staff", equipSlot = 16, minIlvl = 42 },
    { levelMin = 58, levelMax = 68, itemId = 25786, label = "Trinket", equipSlot = 13, minIlvl = 90 },
    { levelMin = 66, levelMax = 70, itemId = 25806, label = "Wand", equipSlot = 18, minIlvl = 100 },
    { levelMin = 68, levelMax = 72, itemId = 31308, label = "Weapon", equipSlot = 16, minIlvl = 115 },
    { levelMin = 76, levelMax = 80, itemId = 44310, label = "Wand", equipSlot = 18, minIlvl = 200 },
    { levelMin = 78, levelMax = 80, itemId = 45128, label = "Staff", equipSlot = 16, minIlvl = 200 },
}
