-- P1 Druid Guide — Horde druid leveling data (3.3.5a)

P1DG = P1DG or {}
P1AG = P1DG

P1DG.FIRST_AID = {
    finalLevel = 40,
    tiers = {
        {
            skillMin = 1, skillMax = 75, levelMin = 1, levelMax = 15,
            label = "Apprentice FA (1-75)",
            clothId = 2589, clothName = "Linen",
            bandageIds = { [1251] = 1, [2581] = 1 },
            goalTotal = 80,
        },
        {
            skillMin = 75, skillMax = 150, levelMin = 15, levelMax = 30,
            label = "Journeyman FA (75-150)",
            clothId = 2592, clothName = "Wool",
            bandageIds = { [3530] = 1, [3531] = 1 },
            goalTotal = 60,
        },
        {
            skillMin = 150, skillMax = 225, levelMin = 30, levelMax = 40,
            label = "Expert FA (150-225)",
            clothId = 4306, clothName = "Silk",
            bandageIds = { [6450] = 2, [6451] = 2, [8544] = 3, [8545] = 3 },
            altClothId = 4338, altClothName = "Mageweave",
            goalTotal = 50,
        },
    },
}

P1DG.HERB_MILESTONES = {
    { levelMin = 1, levelMax = 15, items = {
        { id = 2447, name = "Peacebloom", goal = 20 },
        { id = 765,  name = "Silverleaf", goal = 20 },
    }},
    { levelMin = 15, levelMax = 30, items = {
        { id = 2450, name = "Briarthorn", goal = 15 },
        { id = 785,  name = "Mageroyal", goal = 15 },
    }},
    { levelMin = 30, levelMax = 40, items = {
        { id = 3820, name = "Stranglekelp", goal = 12 },
        { id = 3355, name = "Wild Steelbloom", goal = 12 },
    }},
    { levelMin = 40, levelMax = 50, items = {
        { id = 3818, name = "Fadeleaf", goal = 10 },
        { id = 3821, name = "Goldthorn", goal = 10 },
    }},
}

P1DG.ORE_MILESTONES = {
    { levelMin = 1, levelMax = 15, items = {
        { id = 2770, name = "Copper Ore", goal = 20 },
    }},
    { levelMin = 15, levelMax = 30, items = {
        { id = 2771, name = "Tin Ore", goal = 15 },
        { id = 2772, name = "Iron Ore", goal = 10 },
    }},
    { levelMin = 30, levelMax = 40, items = {
        { id = 3858, name = "Mithril Ore", goal = 10 },
    }},
    { levelMin = 40, levelMax = 50, items = {
        { id = 10620, name = "Thorium Ore", goal = 8 },
        { id = 7912, name = "Solid Stone", goal = 10 },
    }},
}

P1DG.MAT_WATCH = {
    { id = 2939, name = "Ruined Leather Scraps", goal = 20, levelMin = 1, levelMax = 15, hint = "Leatherworking" },
    { id = 2318, name = "Light Leather", goal = 30, levelMin = 10, levelMax = 25, hint = "Skinning" },
    { id = 2320, name = "Coarse Thread", goal = 10, levelMin = 10, levelMax = 20, hint = "Tailoring" },
    { id = 4231, name = "Cured Light Hide", goal = 10, levelMin = 20, levelMax = 35, hint = "Leatherworking" },
}

P1DG.GATHER_FARM = {
    [2447] = { name = "Peacebloom", farms = {
        { zone = "Mulgore", dir = "plains", levelMin = 1, levelMax = 15 },
        { zone = "Durotar", dir = "valley", levelMin = 1, levelMax = 15 },
    }},
    [765] = { name = "Silverleaf", farms = {
        { zone = "Mulgore", dir = "NE", levelMin = 1, levelMax = 15 },
        { zone = "Tirisfal", dir = "fields", levelMin = 1, levelMax = 15 },
    }},
    [2450] = { name = "Briarthorn", farms = {
        { zone = "Barrens", dir = "north", levelMin = 15, levelMax = 25 },
        { zone = "Silverpine", dir = "forest", levelMin = 15, levelMax = 25 },
    }},
    [785] = { name = "Mageroyal", farms = {
        { zone = "Barrens", dir = "Oasis", levelMin = 15, levelMax = 25 },
    }},
    [2770] = { name = "Copper Ore", farms = {
        { zone = "Mulgore", dir = "Red Rocks", levelMin = 1, levelMax = 15 },
        { zone = "Durotar", dir = "caves", levelMin = 1, levelMax = 15 },
    }},
    [2771] = { name = "Tin Ore", farms = {
        { zone = "Barrens", dir = "east ridges", levelMin = 15, levelMax = 25 },
    }},
}

-- BIS by level bracket — ordered by impact (Weapon first). Real Horde druid quest/AH picks.
P1DG.BIS_BRACKETS = {
    {
        levelMin = 10, levelMax = 15,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 15,
              suggest = "Crooked Staff / BoE Agi 2H", itemName = "Crooked Staff",
              source = "Mulgore quests / AH ~5g", priceTier = "cheap",
              why = "Weapon ilvl is your biggest early DPS lever",
              flavor = "Pointy stick go brrr.",
              alt = "Any green +Agi 2H from AH" },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 14,
              suggest = "Rugged Leather Vest", itemName = "Rugged Leather Vest",
              source = "Quest: Dwarven Digging", priceTier = "free",
              why = "Chest armor stops you dying to two boars at once",
              flavor = "Fashion is temporary. Survivability is forever.",
              waypoint = { zone = 215, x = 59.8, y = 49.6, title = "Dwarven Digging" } },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 13,
              suggest = "+Agi legs any green", source = "Quest rewards", priceTier = "free",
              why = "Agi legs = faster kills = faster levels",
              flavor = "Pants with stats beat pants with style." },
            { key = "Trinket", order = 4, equipSlot = 13, minIlvl = 12,
              suggest = "Ritual Totem / any +Sta", source = "Quest drop", priceTier = "free",
              why = "Stamina trinket = fewer corpse runs",
              flavor = "Totem of 'please stop hitting me'." },
        },
    },
    {
        levelMin = 15, levelMax = 20,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 18,
              suggest = "Staff of Nobles", itemName = "Staff of Nobles", itemId = 5201,
              source = "Quest: The Den (Barrens)", priceTier = "free",
              why = "Huge weapon upgrade — Barrens mobs melt faster",
              flavor = "Noble staff for a noble cat.",
              waypoint = { zone = 17, x = 44.2, y = 59.2, title = "The Den" } },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 17,
              suggest = "Savage Trodders / +Agi chest", source = "Quest chain", priceTier = "free",
              why = "Solid quest chest beats random greens",
              flavor = "Trodders: for treading on plainstriders." },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 16,
              suggest = "Leggings of the Fang (dungeon)", itemName = "Leggings of the Fang",
              source = "Wailing Caverns", priceTier = "cheap",
              why = "WC set legs — best feral legs for ages",
              flavor = "Snake pants. Peak fashion.",
              waypoint = { zone = 17, x = 46.0, y = 36.4, title = "Wailing Caverns" } },
            { key = "Hands", order = 4, equipSlot = 10, minIlvl = 15,
              suggest = "+Agi gloves", source = "Quest", priceTier = "free",
              why = "Gloves are easy quest upgrades — don't skip",
              flavor = "Claws not included." },
            { key = "Trinket", order = 5, equipSlot = 13, minIlvl = 15,
              suggest = "Runed Ring / Stamina trinket", source = "Quest", priceTier = "free",
              why = "Extra HP buys time to bandage",
              flavor = "Runes are like tattoos for your trinket slot." },
        },
    },
    {
        levelMin = 20, levelMax = 25,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 22,
              suggest = "Crescent Staff", itemName = "Crescent Staff", itemId = 6630,
              source = "Quest: The Crescent Grove", priceTier = "free",
              why = "Big 20+ weapon spike — worth the detour",
              flavor = "Moon-shaped beatstick.",
              waypoint = { zone = 331, x = 14.2, y = 31.2, title = "Crescent Grove" } },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 21,
              suggest = "Embrace of the Viper", itemName = "Embrace of the Viper",
              source = "Wailing Caverns", priceTier = "cheap",
              why = "WC chest — Agi + stam, cat form dream",
              flavor = "Hug the viper. Wear the viper.",
              waypoint = { zone = 17, x = 46.0, y = 36.4, title = "Wailing Caverns" } },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 20,
              suggest = "+Agi legs ilvl 20+", source = "Barrens quests", priceTier = "free",
              why = "Quest legs tide you over until Fang set",
              flavor = "Any green legs beat no pants. Technically." },
            { key = "Cloak", order = 4, equipSlot = 15, minIlvl = 18,
              suggest = "+Agi cloak", source = "Quest/AH", priceTier = "cheap",
              why = "Cloak Agi is cheap on AH — quick win",
              flavor = "Dramatic cape optional but encouraged." },
            { key = "Trinket", order = 5, equipSlot = 13, minIlvl = 18,
              suggest = "Orb of the Darkmoon", itemName = "Orb of the Darkmoon",
              source = "Darkmoon Faire (optional)", priceTier = "splurge",
              why = "Nice on-use damage if faire is in town",
              flavor = "Carnival loot. Surprisingly deadly.",
              alt = "Any +sta trinket from quests" },
        },
    },
    {
        levelMin = 25, levelMax = 30,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 26,
              suggest = "Mograine's Might (2H) or Agi staff", itemName = "Mograine's Might",
              source = "Scarlet Monastery / AH", priceTier = "splurge",
              why = "Biggest DPS jump until Pole of Ages — worth a SM run or AH splurge",
              flavor = "Paladin left it. Your cat doesn't read lore.",
              alt = "BoE +Agi 2H ilvl 26+ from AH (~15g)",
              waypoint = { zone = 85, x = 83.2, y = 32.4, title = "Scarlet Monastery" } },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 25,
              suggest = "Armor of the Fang", itemName = "Armor of the Fang",
              source = "Wailing Caverns set", priceTier = "cheap",
              why = "Fang chest completes the set vibe — solid Agi",
              flavor = "Full snake cosplay unlocks +10 swagger.",
              waypoint = { zone = 17, x = 46.0, y = 36.4, title = "Wailing Caverns" } },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 24,
              suggest = "+Agi legs ilvl 24+", source = "Thousand Needles", priceTier = "free",
              why = "Needles quest rewards patch weak slots",
              flavor = "Cactus country calls for sturdy pants." },
            { key = "Head", order = 4, equipSlot = 1, minIlvl = 22,
              suggest = "+Agi helm from quests", source = "Quest", priceTier = "free",
              why = "Head slot often empty — quest helms are free power",
              flavor = "Helmets: for looking serious in cat form.",
              alt = "Glowing Lizardscale Cloak if no helm" },
            { key = "Trinket", order = 5, equipSlot = 13, minIlvl = 20,
              suggest = "Horn of the Beast", itemName = "Horn of the Beast", itemId = 5821,
              source = "Quest: The Sacred Flame", priceTier = "free",
              why = "On-use damage + stam — panic button trinket",
              flavor = "Sacred cow horn. Sacredly good.",
              waypoint = { zone = 400, x = 46.1, y = 51.5, title = "The Sacred Flame" } },
        },
    },
    {
        levelMin = 30, levelMax = 40,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 32,
              suggest = "Pole of the Ages", itemName = "Pole of the Ages", itemId = 10648,
              source = "Quest: The Swarm Grows", priceTier = "free",
              why = "Quest weapon that lasts through Desolace grind",
              flavor = "Ancient pole. Modern carnage.",
              waypoint = { zone = 400, x = 77.8, y = 77.2, title = "The Swarm Grows" } },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 30,
              suggest = "Wildheart Vest / +Agi chest", source = "Quest chain", priceTier = "free",
              why = "Bridge chest until Wildheart drops",
              flavor = "Wildheart soon. Patience, young cat.",
              alt = "Wildheart Vest from DM later" },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 28,
              suggest = "+Agi legs ilvl 28+", source = "Desolace / STV", priceTier = "free",
              why = "Keep legs current as you zone-hop",
              flavor = "Jungle legs for jungle rules." },
            { key = "Trinket", order = 4, equipSlot = 13, minIlvl = 25,
              suggest = "Mark of the Chosen", itemName = "Mark of the Chosen",
              source = "Maraudon / quest", priceTier = "cheap",
              why = "Strong trinket for 30+ pull chains",
              flavor = "Chosen by RNG. Eventually.",
              waypoint = { zone = 405, x = 38.8, y = 27.4, title = "Maraudon area" } },
            { key = "Enchants", order = 5, equipSlot = nil, minIlvl = 0,
              suggest = "+Agi cloak, minor stamina boots", source = "AH when spare gold", priceTier = "cheap",
              why = "Cheap enchants add up over long grinds",
              flavor = "Sparkle boots for the sparkle cat." },
        },
    },
    {
        levelMin = 40, levelMax = 50,
        slots = {
            { key = "Weapon", order = 1, equipSlot = 16, minIlvl = 42,
              suggest = "Golem Skull Staff / +Agi 2H", itemName = "Golem Skull Staff", itemId = 9427,
              source = "Uldaman / AH", priceTier = "splurge",
              why = "Massive weapon upgrade for Outland prep",
              flavor = "Skull staff. Very on-brand for a predator.",
              alt = "BoE +Agi 2H ilvl 42+ from AH",
              waypoint = { zone = 3, x = 65.2, y = 36.6, title = "Uldaman" } },
            { key = "Chest", order = 2, equipSlot = 5, minIlvl = 40,
              suggest = "Wildheart Vest", itemName = "Wildheart Vest", itemId = 16706,
              source = "Dire Maul / quest chain", priceTier = "cheap",
              why = "First Wildheart piece — set bonus path begins",
              flavor = "Set pieces: collect them like catnip.",
              waypoint = { zone = 357, x = 59.2, y = 45.8, title = "Dire Maul" } },
            { key = "Legs", order = 3, equipSlot = 7, minIlvl = 40,
              suggest = "Wildheart Kilt", itemName = "Wildheart Kilt", itemId = 16709,
              source = "Dire Maul / STV quests", priceTier = "cheap",
              why = "Kilt + Vest = real set momentum",
              flavor = "Kilt: because druids have standards.",
              waypoint = { zone = 357, x = 59.2, y = 45.8, title = "Dire Maul" } },
            { key = "Head", order = 4, equipSlot = 1, minIlvl = 38,
              suggest = "Wildheart Cowl", itemName = "Wildheart Cowl", itemId = 16707,
              source = "Dire Maul set piece", priceTier = "cheap",
              why = "Cowl completes the cat-in-hood look + stats",
              flavor = "Hood up. Rip down.",
              waypoint = { zone = 357, x = 59.2, y = 45.8, title = "Dire Maul" } },
            { key = "Trinket", order = 5, equipSlot = 13, minIlvl = 35,
              suggest = "Hand of Justice", itemName = "Hand of Justice", itemId = 11815,
              source = "Blackrock Depths (optional)", priceTier = "splurge",
              why = "BiS trinket forever — farm when bored",
              flavor = "Justice hits twice. So do you.",
              alt = "Mark of the Chosen until you can farm BRD",
              waypoint = { zone = 36, x = 80.4, y = 46.8, title = "Blackrock Depths" } },
        },
    },
}

P1DG.AH_TIPS = {
    { levelMin = 11, levelMax = 20, itemId = 2589, itemName = "Linen Cloth",
      tip = "Buy: Linen stacks if <20 total healing", skipIfHave = 20,
      checkBandages = true },
    { levelMin = 11, levelMax = 20, itemId = 118, itemName = "Minor Healing Potion",
      tip = "Buy: Minor Healing Potions — chug between pulls", goal = 10 },
    { levelMin = 15, levelMax = 30, itemId = 2592, itemName = "Wool Cloth",
      tip = "Buy: Wool Cloth stacks for FA 75+", goal = 40 },
    { levelMin = 11, levelMax = 25, itemName = "BoE +Agi weapon",
      tip = "Buy: BoE +Agi 2H Mace ilvl 15-20 (~5g) — big dps boost",
      equipSlot = 16, maxIlvl = 22, isGeneric = true },
    { levelMin = 25, levelMax = 35, itemId = 2459, itemName = "Swiftness Potion",
      tip = "Buy: Swiftness Potions for long travel legs", goal = 5 },
    { levelMin = 40, levelMax = 50, itemId = 3827, itemName = "Mana Potion",
      tip = "Buy: Mana Potions for caster pulls / Innervate gaps", goal = 10 },
}

P1DG.TIPS_BRACKETS = {
    {
        levelMin = 10, levelMax = 15,
        zone = "Mulgore / Bloodhoof",
        flavor = "Baby cat era. The plains are your litter box.",
        rotation = "Cat at 10: FF → Rake → Mangle → Shred\nRip at 3-4cp if mob lives",
        talents = "Next: Furor (shift w/ energy) or Feral Aggression",
        survival = "Bear if 2+ mobs; run below 35% HP",
        quests = "Rite of Vision · Mazzranache · The Ravaged Caravan · Dwarven Digging",
        gather = "Peacebloom/Silverleaf · Copper at Red Rocks",
    },
    {
        levelMin = 15, levelMax = 20,
        zone = "The Barrens",
        flavor = "Barrens: where every quest is 'kill 12 of thing' and you love it.",
        rotation = "Rake → 5cp Rip → Shred filler\nThorns + Mark of the Wild on pull",
        talents = "Next: Sharpened Claws / Feral Swiftness",
        survival = "Bear tough casters; bandage between pulls",
        quests = "The Den (Staff of Nobles) · Raptor Horns · Plainstrider Menace",
        gather = "Briarthorn/Mageroyal north Barrens · Tin ridges",
    },
    {
        levelMin = 20, levelMax = 30,
        zone = "Ashenvale / Stonetalon",
        flavor = "Tree country. Travel Form is your best friend now.",
        rotation = "Travel Form between nodes\nCat: Rake → Rip at 5cp → Ferocious Bite",
        talents = "Next: Feral Charge (30) — save points until then",
        survival = "Bear elites; Innervate before long chains",
        quests = "The Sacred Flame (Horn of Beast) · WC set pieces",
        gather = "Stranglekelp coast · Iron in Stonetalon",
    },
    {
        levelMin = 30, levelMax = 40,
        zone = "Shimmering Flats / Desolace / Arathi",
        flavor = "Desert cat mode. Hydrate (mana) and shred.",
        rotation = "Cat grind: Rake → Rip → Shred\nFa pots on cooldown in bear",
        talents = "Next: Leader of the Pack (if grouping) or Savage Fury",
        survival = "Bear + Fa pot vs 3+ mobs; run at 25%",
        quests = "The Swarm Grows (Pole of Ages) · Reclaiming the Charred Vale",
        gather = "Mithril Flats · Silk/Mageweave for FA Expert",
    },
    {
        levelMin = 40, levelMax = 50,
        zone = "Tanaris / Feralas / STV",
        flavor = "Endgame stretch. Wildheart or bust.",
        rotation = "Wildheart cat: maintain Rip/Rake\nShift bear for pull, cat for burn",
        talents = "Next: Predatory Strikes · prep 60 mount gold",
        survival = "Bear STV elites; always Mark/Thorns",
        quests = "Wildheart set in Dire Maul · Zul'Farrak for XP",
        gather = "Fadeleaf/Goldthorn STV · Thorium later zones",
    },
}

-- Optimal path bullets — impact order, gold AH assumed (buy BIS at level gate)
P1DG.PATH_STEPS = {
    { level = 10, impact = 100, type = "hint", maxLevel = 11,
      text = "Complete Cat Form quest chain (Mulgore) — unlock feral leveling",
      flavor = "Quest chain → cat form → actual fun begins." },
    { level = 10, impact = 98, type = "spell", spellId = 768,
      text = "Train Cat Form — pull in cat, not bear",
      flavor = "Bear is for panic. Cat is for living." },
    { level = 10, impact = 95, type = "gear", equipSlot = 16, minIlvl = 15, itemId = nil,
      text = "AH: +Agi 2H staff/mace ilvl 15+ (gold budget — buy immediately)",
      flavor = "~5g for double the face-clawing. Worth it." },
    { level = 10, impact = 90, type = "profession", skill = 1,
      text = "Train First Aid — bandage between pulls",
      flavor = "Cloth into HP. Alchemy who?" },
    { level = 12, impact = 88, type = "spell", spellId = 1822,
      text = "Train Rake — apply on pull, maintain DoT",
      flavor = "Bleed first. Questions later." },
    { level = 14, impact = 86, type = "spell", spellId = 33876,
      text = "Train Mangle (Cat) — keep debuff up (+30% bleeds)",
      flavor = "Mangle = bleeds hurt more. Mandatory cat math." },
    { level = 14, impact = 84, type = "hint", maxLevel = 16,
      text = "Rotation: FF pull → Rake → Mangle → Shred to 3-4cp → Rip if mob lives",
      flavor = "Rip if they live. Bite if they don't. Cat judgement." },
    { level = 16, impact = 82, type = "gear", equipSlot = 16, minIlvl = 18, itemId = 5201,
      text = "Quest/AH: Staff of Nobles (The Den, Barrens)",
      flavor = "Barrens weapon spike. Do The Den.",
      waypoint = { zone = 17, x = 44.2, y = 59.2, title = "Staff of Nobles" } },
    { level = 18, impact = 80, type = "consume", itemId = 118, goal = 10,
      text = "AH: Minor Healing Potions ×10 — zero downtime",
      flavor = "Potions = no spirit run to corpse." },
    { level = 20, impact = 78, type = "spell", spellId = 783,
      text = "Travel Form — quest travel speed huge",
      flavor = "Four legs good. Two legs for losers." },
    { level = 20, impact = 76, type = "gear", equipSlot = 16, minIlvl = 22, itemId = 6630,
      text = "Quest: Crescent Staff (Crescent Grove) or AH equivalent",
      flavor = "Moon staff beats walking. Obviously.",
      waypoint = { zone = 331, x = 14.2, y = 31.2, title = "Crescent Staff" } },
    { level = 22, impact = 74, type = "hint", maxLevel = 24,
      text = "Barrens: Rake→Rip at 5cp on elites; bear+Swipe for 3+ mobs",
      flavor = "One mob? Cat. Three mobs? Bear says hi." },
    { level = 24, impact = 72, type = "spell", spellId = 5217,
      text = "Tiger's Fury on CD when energy <40",
      flavor = "Empty energy? ROAR and pretend you meant it." },
    { level = 26, impact = 70, type = "gear", equipSlot = 13, minIlvl = 20, itemId = 5821,
      text = "Quest: Horn of the Beast trinket (Sacred Flame)",
      flavor = "Free trinket. Sacred Flame chain. Do it.",
      waypoint = { zone = 400, x = 46.1, y = 51.5, title = "Horn of the Beast" } },
    { level = 28, impact = 68, type = "gear", equipSlot = 7, minIlvl = 24, itemId = 10410,
      text = "Dungeon/AH: Leggings of the Fang (WC set)",
      flavor = "Snake pants from WC. Run it twice. RNG permitting.",
      waypoint = { zone = 17, x = 46.0, y = 36.4, title = "Leggings of the Fang" } },
    { level = 30, impact = 66, type = "spell", spellId = 49376,
      text = "Feral Charge (Cat) — gap close, save shift time",
      flavor = "Gap closer unlocked. Mobs can't run. You can." },
    { level = 32, impact = 64, type = "gear", equipSlot = 16, minIlvl = 32, itemId = 10648,
      text = "Quest: Pole of the Ages (Thousand Needles)",
      flavor = "Big stick from bug quest. Classic WoW.",
      waypoint = { zone = 400, x = 77.8, y = 77.2, title = "Pole of the Ages" } },
    { level = 34, impact = 62, type = "profession", skill = 150,
      text = "FA Expert 150 — Silk/Mageweave bandage stock",
      flavor = "Expert bandages = fewer embarrassing deaths." },
    { level = 36, impact = 60, type = "hint", maxLevel = 40,
      text = "Desolace/STV: cat single-target; mark+thorns on every pull",
      flavor = "Mark everything. Thorns everything. Cat everything else." },
    { level = 40, impact = 58, type = "gear", equipSlot = 5, minIlvl = 40, itemId = 16706,
      text = "AH/DM: Wildheart Vest — first set piece",
      flavor = "Wildheart #1. The addiction begins.",
      waypoint = { zone = 357, x = 59.2, y = 45.8, title = "Wildheart Vest" } },
    { level = 42, impact = 56, type = "gear", equipSlot = 16, minIlvl = 42, itemId = 9427,
      text = "AH: Golem Skull Staff (Uldaman) — big weapon upgrade",
      flavor = "Skull on a stick. Peak feral aesthetic.",
      waypoint = { zone = 3, x = 65.2, y = 36.6, title = "Golem Skull Staff" } },
    { level = 44, impact = 54, type = "gear", equipSlot = 7, minIlvl = 40, itemId = 16709,
      text = "AH: Wildheart Kilt + Cowl — complete set bonuses",
      flavor = "Collect the set. Look like you mean business." },
    { level = 46, impact = 52, type = "consume", itemId = 3827, goal = 15,
      text = "AH: Mana Potions for long quest chains",
      flavor = "Mana pots for when Innervate is on vacation." },
    { level = 48, impact = 50, type = "gear", equipSlot = 13, minIlvl = 35, itemId = 11815,
      text = "Optional AH: Hand of Justice (BiS trinket long-term)",
      flavor = "Farm BRD when bored. Until then, Horn is fine." },
}

P1DG.GOLD_AH_BIS = {
    { levelMin = 10, levelMax = 18, itemId = 5201, label = "Staff", equipSlot = 16, minIlvl = 18 },
    { levelMin = 18, levelMax = 26, itemId = 6630, label = "Staff", equipSlot = 16, minIlvl = 22 },
    { levelMin = 24, levelMax = 34, itemId = 5821, label = "Trinket", equipSlot = 13, minIlvl = 20 },
    { levelMin = 28, levelMax = 38, itemId = 10410, label = "Legs", equipSlot = 7, minIlvl = 24 },
    { levelMin = 32, levelMax = 42, itemId = 10648, label = "Weapon", equipSlot = 16, minIlvl = 32 },
    { levelMin = 40, levelMax = 50, itemId = 16706, label = "Chest", equipSlot = 5, minIlvl = 40 },
    { levelMin = 42, levelMax = 50, itemId = 9427, label = "Weapon", equipSlot = 16, minIlvl = 42 },
}